name:          Przewodnik kodu według @mdo
description:   Standardy elastycznego, trwałego i zrównoważonego HTML i CSS. 
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
